apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-script
  template:
    metadata:
      labels:
        app: python-script
    spec:
      containers:
      - name: python-script
        image: zaikron/commupy:latest
